---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Create /data directory
      ansible.builtin.file:
        path: /data
        state: directory
        mode: "0755"

  roles:
    - role: java
    - role: kafka
    - role: jmx_exporter
