version: '3'

vars:
  TERRAFORM_DIR: ./tests/terraform
  INVENTORY_TEST: ./inventories/test/hosts.yml
  INVENTORY_PROD: ./inventories/production/hosts.yml

includes:
  ansible: ./.taskfiles/ansible.yml
  test: ./.taskfiles/test.yml
  test:infra: ./.taskfiles/test-infra.yml

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
