version: '3'

vars:
  INVENTORY_PROD: ./inventories/production/hosts.yml

includes:
  ansible: ./.taskfiles/ansible.yml

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
