---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: Check Kafka exporter service is running
      ansible.builtin.systemd:
        name: kafka_exporter
      register: kafka_exporter_service
      failed_when: kafka_exporter_service.status.ActiveState != "active"

    - name: Wait for Kafka exporter port
      ansible.builtin.wait_for:
        port: 9308
        timeout: 60

    - name: Check Kafka exporter metrics endpoint
      ansible.builtin.uri:
        url: http://localhost:9308/metrics
        return_content: true
      register: kafka_exp_metrics
      retries: 5
      delay: 10

    - name: Verify Kafka exporter metrics
      ansible.builtin.assert:
        that:
          - "'kafka_brokers' in kafka_exp_metrics.content"
        fail_msg: "Kafka exporter is not returning expected metrics"
        success_msg: "Kafka exporter is working correctly"
