---
all:
  children:
    kafka:
      hosts:
        ec2-3-0-99-176.ap-southeast-1.compute.amazonaws.com:
          kafka_node_id: 1
          kafka_internal_ip: 10.100.1.42
      vars:
        kafka_quorum_voters: "1@10.100.1.42:9093"
    monitoring:
      hosts:
        monitoring-staging:
          ansible_host: <monitoring-vm-private-ip>
      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: ~/.ssh/id_ed25519
