Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"

  (1..3).each do |i|
    config.vm.define "kafka-#{i}" do |node|
      node.vm.hostname = "kafka-#{i}"
      node.vm.network "private_network", ip: "192.168.56.#{10 + i}"

      node.vm.provider "virtualbox" do |vb|
        vb.name = "kafka-#{i}"
        vb.memory = 4096
        vb.cpus = 2

        # Add 10GB data disk for Kafka storage
        data_disk = ".vagrant/kafka-#{i}-data.vdi"
        unless File.exist?(data_disk)
          vb.customize ['createmedium', 'disk', '--filename', data_disk,
                        '--size', 10240, '--format', 'VDI']
        end
        vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller',
                      '--port', 1, '--type', 'hdd', '--medium', data_disk]
      end
    end
  end
end
