---
- name: Converge
  hosts: kafka
  become: true

  pre_tasks:
    - name: Gather facts
      ansible.builtin.setup:
        gather_subset:
          - hardware
          - network

  roles:
    - role: java
    - role: kafka
    - role: jmx_exporter
    - role: kafka_exporter
