---
all:
  children:
    kafka:
      hosts:
        kafka-1:
          ansible_host: 192.168.56.11
          kafka_node_id: 1
          kafka_internal_ip: 192.168.56.11
      vars:
        ansible_user: vagrant
        ansible_ssh_private_key_file: "{{ inventory_dir }}/../../tests/vagrant/.vagrant/machines/{{ inventory_hostname }}/virtualbox/private_key"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
        kafka_quorum_voters: "1@192.168.56.11:9093"
        kafka_default_replication_factor: 1
        kafka_min_insync_replicas: 1
        kafka_offsets_topic_replication_factor: 1
        kafka_transaction_state_log_replication_factor: 1
        alloy_victoriametrics_url: "http://192.168.56.20:8428"
        alloy_loki_url: "http://192.168.56.20:3100"
        alloy_environment: "vagrant"
        kafka_local_tarball: "{{ inventory_dir }}/../../files/kafka_2.13-4.1.1.tgz"
    monitoring:
      hosts:
        monitoring-1:
          ansible_host: 192.168.56.20
      vars:
        ansible_user: vagrant
        ansible_ssh_private_key_file: "{{ inventory_dir }}/../../tests/vagrant/.vagrant/machines/{{ inventory_hostname }}/virtualbox/private_key"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    redpanda_console:
      hosts:
        redpanda-console-1:
          ansible_host: 192.168.56.30
      vars:
        ansible_user: vagrant
        ansible_ssh_private_key_file: "{{ inventory_dir }}/../../tests/vagrant/.vagrant/machines/{{ inventory_hostname }}/virtualbox/private_key"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
        redpanda_console_kafka_brokers: "192.168.56.11:9092"
