---
all:
  children:
    kafka:
      hosts:
        kafka-1.internal:
          kafka_node_id: 1
        kafka-2.internal:
          kafka_node_id: 2
        kafka-3.internal:
          kafka_node_id: 3
      vars:
        kafka_quorum_voters: "1@kafka-1.internal:9093,2@kafka-2.internal:9093,3@kafka-3.internal:9093"
