---
all:
  children:
    kafka:
      hosts:
        ec2-54-179-198-162.ap-southeast-1.compute.amazonaws.com:
          kafka_node_id: 1
          kafka_internal_ip: 10.100.2.86
        ec2-54-179-72-89.ap-southeast-1.compute.amazonaws.com:
          kafka_node_id: 2
          kafka_internal_ip: 10.100.2.118
        ec2-54-179-151-161.ap-southeast-1.compute.amazonaws.com:
          kafka_node_id: 3
          kafka_internal_ip: 10.100.2.117
      vars:
        kafka_quorum_voters: "1@10.100.2.86:9093,2@10.100.2.118:9093,3@10.100.2.117:9093"
    monitoring:
      hosts:
        monitoring-prod:
          ansible_host: <monitoring-vm-private-ip>
      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: ~/.ssh/id_ed25519
