---
all:
  children:
    kafka:
      hosts:
        ec2-13-250-10-251.ap-southeast-1.compute.amazonaws.com:
          kafka_node_id: 1
          kafka_internal_ip: 172.31.32.41
        ec2-52-77-211-175.ap-southeast-1.compute.amazonaws.com:
          kafka_node_id: 2
          kafka_internal_ip: 172.31.45.161
        ec2-47-128-224-132.ap-southeast-1.compute.amazonaws.com:
          kafka_node_id: 3
          kafka_internal_ip: 172.31.43.127
      vars:
        kafka_quorum_voters: "1@172.31.32.41:9093,2@172.31.45.161:9093,3@172.31.43.127:9093"
