---
jmx_exporter_version: "1.0.1"
jmx_exporter_port: 7071
jmx_exporter_install_dir: "/opt/jmx_exporter"
jmx_exporter_config_file: "{{ kafka_config_dir | default('/etc/kafka') }}/jmx-exporter.yml"
jmx_exporter_jar: "jmx_prometheus_javaagent-{{ jmx_exporter_version }}.jar"
jmx_exporter_download_url: "https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/{{ jmx_exporter_version }}/{{ jmx_exporter_jar }}"
