---
galaxy_info:
  author: your_name
  description: Install JMX Exporter for Kafka metrics
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - noble

dependencies: []
